
GET http://localhost:8000/

###

###
GET http://localhost:8000/restaurant

###

GET http://localhost:8000/users

###
POST http://localhost:8000/users
Content-Type: application/json

{
    "email": "trial@gmail.com",
    "password": "12342",
    "firstname": "Trial",
    "lastname": "Trial",
    "phone": "+25471521254",
    "createdAt": "2024-06-06T00:00:00.000Z",
    "updatedAt": "2024-06-06T00:00:00.000Z"
}
###
PUT http://localhost:8000/users/1
Content-Type: application/json

{
    "fullname": "Alexa"
}
###
DELETE http://localhost:8000/users/"1"

###
GET http://localhost:8000/orders

###
GET http://localhost:8000/states

###

POST http://localhost:8000/states
Content-Type: application/json

{
    "name": "Kisumu",
    "code": "20100"
}

###
GET http://localhost:8000/menuItem

###

GET http://localhost:8000/category 


###
GET http://localhost:8000/comments

###

POST http://localhost:8000/comments
Content-Type: application/json

{
    "orderId": 1,
    "userId": 2,
    "commentText": "Great",
    "isComplaint": true,
    "isPraise": false,
    "createdAt": 06 06 2024,
    "updatedAt": 06 06 2024
}