
GET http://localhost:8000/

###

#---- Restaurant---#
###
GET http://localhost:8000/restaurant

#---- Users---#
###
GET http://localhost:8000/users

###
POST http://localhost:8000/users
Content-Type: application/json

{
    "email": "example@gmail.com",
    "password": "example",
    "firstName": "John",
    "lastName": "Doe",
    "phone": "+25471521254",
    "createdAt": "2024-06-06",
    "updatedAt": "2024-06-06"
}
###
PUT http://localhost:8000/users/8
Content-Type: application/json

{
    "firstName": "Alexa"
}
###
DELETE http://localhost:8000/users/7

#---- Orders---#
###
GET http://localhost:8000/orders

#---- States---#
###
GET http://localhost:8000/states

###

POST http://localhost:8000/states
Content-Type: application/json

{
    "name": "Kisumu",
    "code": "20100"
}

###
PUT http://localhost:8000/states/1
Content-Type: application/json

{
    "name": "Nakuru"
}
###
DELETE http://localhost:8000/states/"1"

#---- Menu item---#
###
GET http://localhost:8000/menuItem

#---- Category---#
###
GET http://localhost:8000/category 

#---- Comments---#
###
GET http://localhost:8000/comments

###

POST http://localhost:8000/comments
Content-Type: application/json

{
    "orderId": 1,
    "userId": 2,
    "commentText": "Great",
    "isComplaint": true,
    "isPraise": false,
    "createdAt": "2024-06-06",
    "updatedAt": "2024-06-06"
}
###
PUT http://localhost:8000/comments/1
Content-Type: application/json

{
    "fullname": "Alexa"
}
###
DELETE http://localhost:8000/comments/"1"

#---- Address---#
###
GET http://localhost:8000/addresses

###

POST http://localhost:8000/addresses
Content-Type: application/json

{
    "streetAddress1": 1,
    "streetAddress2": 2,
    "zipCode": 20210,
    "deliveryInstructions": "free",
    "userId": 2,
    "cityId": 3,
    "createdAt": "2024-06-06",
    "updatedAt": "2024-06-06"
}

###
PUT http://localhost:8000/addresses/1
Content-Type: application/json

{
    "fullname": "Alexa"
}
###
DELETE http://localhost:8000/addresses/"1"